export const ADD_ERROR = 'ADD_ERROR';
export const ADD_SUCCESS = 'ADD_SUCCESS';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REQUEST_START = 'REQUEST_START';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_ERROR = 'REQUEST_ERROR';

export const START_LOGIN_USER = 'START_LOGIN_USER';
export const SUCCESS_LOGIN_USER = 'SUCCESS_LOGIN_USER';
export const ERROR_LOGIN_USER = 'ERROR_LOGIN_USER';
export const START_SIGNUP_USER = 'START_SIGNUP_USER';
export const SUCCESS_SIGNUP_USER = 'SUCCESS_SIGNUP_USER';
export const ERROR_SIGNUP_USER = 'ERROR_SIGNUP_USER';
export const START_LOGOUT_USER = 'START_LOGOUT_USER';
export const SUCCESS_LOGOUT_USER = 'SUCCESS_LOGOUT_USER';
export const ERROR_LOGOUT_USER = 'ERROR_LOGOUT_USER';

export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const SET_EDITING_STATUS_TO_PROJECT = 'SET_EDITING_STATUS_TO_PROJECT';
export const UNSET_EDITING_STATUS_TO_PROJECT = 'UNSET_EDITING_STATUS_TO_PROJECT';
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS';
export const REMOVE_PROJECT_SUCCESS = 'REMOVE_PROJECT_SUCCESS';

export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const SET_EDITING_STATUS_TO_TASK = 'SET_EDITING_STATUS_TO_TASK';
export const UNSET_EDITING_STATUS_TO_TASK = 'UNSET_EDITING_STATUS_TO_TASK';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS';

export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS';

export const ADD_FILE = 'ADD_FILE';
export const REMOVE_FILE = 'REMOVE_FILE';
